# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UuXJl4_uhbu_N4mpJi__csY9gJsVmRhk
"""

import pandas as pd
baza={
    "Ismi":[   "Donyorbek", "Dilmurod", "Esonali","Faxriyor" , "Faxriddin", "Alisher"  ],
    "Manzili":[   "Oltiariq", "Oltiariq" , "Olriariq" ,"Shaxrixon", "Andijon" ,"Farg'ona"   ],
    "Yoshi":[ "19", "19" ,"19" , "19", "20", "24"  ]


}
db=pd.DataFrame(baza)
print(db)

db.to_excel("Tatuff.xlsx")